site_name: CASTEP Docs
nav:
   - Home: 'index.md'
   - 'Documentation':
      - 'Getting Started':
        - 'Introduction': 'documentation/Getting_Started/intro.md'
        - 'Command line help': 'documentation/Getting_Started/built_in_help.md'
      - 'Ground State':
        - 'Overview':  'documentation/Groundstate/intro.md'
        - 'Dispersion Corrections': 'documentation/Groundstate/dftd.md'
        - 'Spin Orbit Coupling': 'documentation/Groundstate/soc.md'
      - 'Geometry Optimisation':
        - 'Overview': 'documentation/Geometry_Optimisation/overview.md'
        - 'Keywords': 'documentation/Geometry_Optimisation/keywords.md'
        - 'Constraints': 'documentation/Geometry_Optimisation/constraints.md'
        - 'Files': 'documentation/Geometry_Optimisation/files.md'
        - 'Tools': 'documentation/Geometry_Optimisation/tools.md'
      - 'Molecular Dynamics':
        - 'Overview': 'documentation/Molecular_Dynamics/overview.md'
      - 'Spectral':
        - 'Overview': 'documentation/Spectral/overview.md'
        - 'Keywords': 'documentation/Spectral/keywords.md'
        - 'Restarts': 'documentation/Spectral/restarts.md'
      - 'Vibrations':
        - 'Vibrations': 'documentation/Vibrations/overview.md'
      - 'NMR':
        - 'NMR Overview': 'documentation/NMR/NMR_overview.md'
      - 'EPR':
        - 'EPR Overview': 'documentation/EPR/overview.md'
      - 'XRD': 'documentation/XRD/overview.md'
      - 'TDDFT':
        - 'TDDFT Overview': 'documentation/TDDFT/overview.md'
      - 'Pseudopotentials':
        - 'Theory':   'documentation/Pseudopotentials/theory.md'
        - 'Overview': 'documentation/Pseudopotentials/overview.md'
        - 'Headers': 'documentation/Pseudopotentials/reading_headers.md'
        - 'OTFG string': 'documentation/Pseudopotentials/otfg_string.md'
   - 'Tutorials':
      - 'Bonding and Charge':
        - 'Plotting Charge Density': 'tutorials/Bonding_and_Charge/charge_density.md'
        - 'Population Analysis': 'tutorials/Bonding_and_Charge/mulliken_population.md'
      - 'Bands and DOS':
        - 'Plotting - CASTEP tools': 'tutorials/Bands_and_DOS/plotting_perl.md'
        - 'Plotting - SUMO': 'tutorials/Bands_and_DOS/plotting_sumo.md'
        -  'Semiconductors':      'tutorials/Bands_and_DOS/semiconductors.md'
        -  'Metals':      'tutorials/Bands_and_DOS/metals.md'
        -  'Magnetic Materials':      'tutorials/Bands_and_DOS/magnetic.md'
      - 'Dispersion corrections': 'tutorials/dispersion_corrections/castep-ase-dispersion-tutorial.md'
      - 'NMR Shielding': 'tutorials/NMR_shielding.md'

theme:
  name: material
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - footnotes
extra_css:
  - stylesheets/extra.css
